### ISSUE TITLE
Complete Options & Commands Work

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#2616]
Umbrella issue for all the console-related improvements that are needed for 3.0. The command/options changes introduced a lot of changes here, and we need to make sure that the regressions aren't too severe:

- UX for Keyboard Shortcuts
  - [ ] If I press `b` in the flow list, `:cut.save s.content|@focus` appears. It's unclear what I as a user am supposed to do here. (#2650)
  - [ ] Same for `|`, where`script.run @focus` appears. If I naively press enter it (too) briefly displays "usage: script.run flowspec str". It is at no point obvious that str is for a filename. Same goes for `e` export, `w` save file, etc. (#2198)
  - [ ] ctrl+l is a shortcut for "send cuts to clipboard" in the flow list. It is not really clear what that means. (#2650)
- Command List (Shift+C) UX is a bit rough around the edges...
  - [ ] `console.bodyview` - doesn't mention that `str` must be "request" or "response", crashes when I just try `console.bodyview @focused vim`. (#2651) 
  - [ ] `console.choose/console.choose.cmd`: Invoking them with zero parameters crashes mitmproxy. It's not clear how I can specify `[str]`. Where/how do I specify the command that is next invoked and how are args passed - positional? (#2652)
  - [ ] `console.edit.focus`: Needs docs and an example - not sure what it does at the moment. (#2653)
  - [ ] `console.edit.focus.options  ->` Needs docs and an example - not sure what it does at the moment. "Command returned too much data for display". (#2653, #2654)
  - [ ] `console.flowview.mode.set` is confusingly named, and should probably be `.prompt`. (#2655)
- Key binding issues
  - [ ] "shift tab" to focus on the next pane doesn't work for me - https://github.com/Microsoft/WSL/issues/1770

Given that we _really really_ want to get out 3.0 soon-ish, I would be strongly in favor of not exposing commands to users (of course continue using them internally) for 3.0 and ship it with 4.0. The changes for that would be negligible and we can really focus on getting commands right after that. There really is a lot lot lot of potential in the commands feature, and I think we'd do ourselves a favor if we introduce it in a state where it's not so easy to hate.

@mitmproxy/devs, thoughts?

**Comment by Kriechi** [comment]
Yes, the new console commands (and UX) is still unfinished and needs some testing before we should release it. The core components are there and seem to be solid. The UI/UX can benefit from some love though 😄 

That said, I think it could be a major feature for 3.0 - if we find the time do to the required work.
Maybe we can also start putting together a changelog for 3.0, and then decide if & what makes it into the release.

**Comment by mhils** [comment]
We have 900 commits on master since 2.0, so I think featurewise we're more than packed for 3.0 (options, contentviews, mitmweb, ...). 

I am really looking forward to have commands in mitmproxy, as it's going to be a fantastic feature. I just think that fixing the command ux will take a bit really, and we're far behind the 2-month schedule we agreed on at some point. There's really nothing that stops us from finishing commands immediately after 3.0 is out and ship 4.0 as soon as it's finished.

**Comment by cortesi** [comment]
Thanks for the detailed feedback list, Max - it's very useful. Hiding commands for 3.0 is not an option - it's the core interaction paradigm now, so we must push on. Luckily, many of the issues you list are easily fixed and go away once we've taken the immediate next steps in the roadmap, added documentation, and so forth. So, much of this is just due to the fact that I had to step back from things in mid-flight, so to speak, which is unfortunate. 

Some notes:

- Path will be more obvious once we have fixed #2198, which will let us show "path" in the help prompts.
- A few of these are due to the fact that you don't know what the cuts mechanism does - which is not surprising because it's not documented. This will be fixed soon. 
- A few of the comments for the command list shows that you're interpreting this differently from the way I intended. This is meant to be a command palette, with documentation for all commands, including internal commands. It's the documentation and the playground from which people can hopefully assemble their own complex commands and key bindings. From that perspective, it doesn't make sense to say that `console.command` is not too useful in the list, or that `console.choose` is only useful internally, or that you would just press q/Q rather than select the quit command from the command palette. 
- Many of these issues here might be fixed if we have a help string for each keyboard shortcut, which is displayed if a user prompt results. I don't want to hide the underlying commands entirely, though, because we do want people to be able to inspect them and grow to use them directly.

I'm going to edit your list to add issues for items that translate into obvious actions, and to trim items that don't make sense to me. Let's keep the list up to date as we move to 3.0.

**Comment by cortesi** [comment]
Also, I see you have two key binding issues - up/down in the keybinding list, and shift-tab to switch focus pane. Both of these work for me, so if you could open an issue with some more info on how I can reproduce those, that would be excellent.

**Comment by cortesi** [comment]
- [ ] Pressing `r` shows `[cplayback:1]` for some reason. (#2621)

This is expected - pressing "r" adds one flow (the current focus) to the client replay buffer. Once the replay buffer is empty, the playback buffer indicator goes away. You can add an arbitrary number of flows to the replay buffer with a flow specification to the `replay.client` command.

**Comment by cortesi** [comment]
- [ ] `console.grideditor.{add,delete,editor,insert,readfilereadfile_escaped}`: "Not in a grideditor" even though I'm in a grideditor. Bug?

While you're viewing the command palette, you're not in a grid editor. Try typing these commands (or binding them to a key), and using them in one of the grid editors (e.g. editing cookies). Works for me.

**Comment by cortesi** [comment]
- [ ] `console.flowview.mode` "Not viewing a flow", even though I was in the flow view before pressing Shift+C.

This is the command palette thing again. Works for me while viewing a flow.

**Comment by cortesi** [comment]
- [ ] `console.flowview.mode.set` Shouldn't this take an argument? Also "Not viewing a flow".

Works while viewing a flow. The name here is clumsy, though - it pops up a prompt to allow the user to select the flow view mode. This could be renamed to `console.flowview.mode.prompt` and a corresponding `.set` command can be added that takes an argument.

**Comment by cortesi** [comment]
- [ ] `console.edit.focus`: Needs docs and an example - not sure what it does at the moment. Doesn't modify the query of the currently focused flow.  
- [ ] `console.edit.focus.options  ->` Needs docs and an example - not sure what it does at the moment. "Command returned too much data for display".

Both of these work as expected - the bug is that they need proper docstrings. The `console.edit.focus` command starts editing a component of the current focus. The `console.edit.focus.options` returns the list of valid options that can be passed to `console.edit.focus`, and is intended to be used in scripts to prompt the user. You can see this in action in the default key binding for "e", which first prompts the user, then executes the command with the user's choice:

        console.choose.cmd Part console.edit.focus.options
        console.edit.focus {choice}

The "too much data" thing is worth thinking about. Some commands that have output that should be consumed programmatically return a lot of data, and we don't necessarily just want to dump it in the console. We can probably do better than the current message, though.

**Comment by cortesi** [comment]
Everything here has either been addressed, or has a separate open ticket. Closing this to clear the milestone.
