### ISSUE TITLE
Tracking Issue: Local Redirect Mode

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#6531]
We're adding _local redirect mode_ to mitmproxy, which makes it possible to transparently intercept local applications.
See https://github.com/mitmproxy/mitmproxy/issues/6332 and https://mitmproxy.org/posts/local-redirect/macos/ for some background.

#### macOS (lead: @emanuele-em)
   - [x] Traffic Redirection (https://mitmproxy.org/posts/local-redirect/macos/)
   - [x] Certificate Installation Routines
   - [ ] Process Enumeration
#### Windows (lead: @mhils)
   - [x] Traffic Redirection (TBA)
   - [ ] Certificate Installation Routines
   - [x] Process Enumeration
#### Linux (lead: @decathorpe)
   - [ ] Traffic Redirection
   - [ ] Certificate Installation Routines
   - [ ] Process Enumeration
#### General
 - [x] CLI Integration (https://github.com/mitmproxy/mitmproxy/issues/6332)
 - [ ] Web UI Integration
 - [ ] Automatic Cert Install
 - [ ] Updated Proxy Mode Docs

Help with any of this is more than welcome, please reach out to us individually or comment below! 😃

**Comment by Khushikela29** [comment]
Hii!! 
How can i help you with the issue ??

**Comment by allaboutevemirolive** [comment]
Hey @decathorpe , I would like to take part in implementing `local redirect mode` for linux.

**Comment by emanuele-em** [comment]
These days i was trying to play a little bit with **ebpf** for `local mode` on linux and below i can share some information i understood:
- **xdp** is the lowest level program, it's very fast, only input data, and you can't get the pid (at that level it hasn't been assigned to the packet yet) 🔴
- **tc** seems to be the best solution, but again I haven't found a trivial way to get the pid directly ( other than to map ports and pids, but that doesn't seem like a robust solution, _does it?_ @mhils @decathorpe) 🟠
- maybe there is a solution by combining a **kprobe** with a **tc** but I still haven't figured out how.

The good thing is that at the moment I was able to show all the packets 🥳 

if anyone has opinions or ideas that would be great

**Comment by decathorpe** [comment]
> These days i was trying to play a little bit with **ebpf** for `local mode` on linux and below i can share some information i understood:
> 
> * **xdp** is the lowest level program, it's very fast, only input data, and you can't get the pid (at that level it hasn't been assigned to the packet yet) 🔴
> 
> * **tc** seems to be the best solution, but again I haven't found a trivial way to get the pid directly ( other than to map ports and pids, but that doesn't seem like a robust solution, _does it?_ @mhils @decathorpe) 🟠
> 
> * maybe there is a solution by combining a **kprobe** with a **tc** but I still haven't figured out how.
> 
> 
> The good thing is that at the moment I was able to show all the packets 🥳
> 
> if anyone has opinions or ideas that would be great

That's about as far as I got with my investigations as well - XDP would be nice (and ... it's actually well-documented, compared to the alternatives), but it's incoming packets only, and too low-level for our purposes.

There's a project that does a similar thing (with Python / bcc / eBPF): <https://github.com/quarkslab/peetch>
So it appears that it *is* possible to do a MITM proxy via eBPF *somehow*, but I don't know how robust it is.

**Comment by emanuele-em** [comment]
From what I can see:
1. The [kprobe](https://github.com/quarkslab/peetch/blob/master/peetch/ebpf_programs/peetch_kprobes.c) get the pid and the filename and cache them in a map
2. The [Uprobe](https://github.com/quarkslab/peetch/blob/master/peetch/ebpf_programs/peetch_uprobes.c) get some informations related to ssl/tls
3. The actual [proxy](https://github.com/quarkslab/peetch/blob/master/peetch/ebpf_programs/peetch_proxy.c) check if the pid is in the cache (so it avoids to intercept itself) and then does the rest 

I think we can use a similar approach, without the `uprobe` and using a `tc` program instead of a [socket_filter](https://github.com/quarkslab/peetch/blob/2ec684d103687d1e5435e1a09e427272962b35d9/peetch/ebpf_programs/peetch_proxy.c#L18) so we can intercept packets at a lower level.

let me know what you think

**Comment by emanuele-em** [comment]
Little update:
I'm facing with 3 main challenges at the moment and I have a possible and tested solution for only two of them:
1. 🟢 **Intercept packet at kernel level and send them to user level**: at the moment I'm able to intercept packet thanks to `TC classifier`, a ebpf program. After the interception I write the entire packet on a `PerCPUArray` and I send the pointer to that array to the userspace (I can't send the entire packet directly because there is a size limit of 512b). When the packet is on the user space I'm free to do everything with it (send it to the mitmproxy core etc)
[[CODE kernel](https://github.com/emanuele-em/mitmproxy_linux/blob/947d834a6745cafd4c003498d23f01b821a2d8c5/only-interception/only-interception-ebpf/src/main.rs#L8C1-L24C2) | [CODE user](https://github.com/emanuele-em/mitmproxy_linux/blob/947d834a6745cafd4c003498d23f01b821a2d8c5/only-interception/only-interception/src/main.rs#L74C5-L104C6)]
2. 🟢 **Intercept only packet with a specific pid or with a specific process name**: the idea is to have a list (shared with the kernel space) of whitelisted pid (or process name), I can check the pid on kernel space, if the pid is in the white list, I can intercept it, otherwise I can just ignore it.
3. 🟠 **Reinject packet**: This is the most challenging part until now. I can't do the reverse of the point one, because the kernel `TC Context` is created only when the packet is created, I can't create it from scratch and I can't force it. I thing a possible solution could be change the source of the packet to inject, pretending that it comes directly from the original process (maybe with `BPF_CGROUP_INET4_GETPEERNAME`)

**Comment by mhils** [comment]
@user-name-is-taken: iptables would indeed get us pretty far, but it does not allow us to filter by process name for example.

The command you posted is also rewriting the destination address (which wouldn't work for us). There are ways around that (https://docs.mitmproxy.org/stable/howto-transparent/#work-around-to-redirect-traffic-originating-from-the-machine-itself), but at least the process name limitation remains.

**Comment by q2dg** [comment]
> Is there a reason to not use iptables? [for example](https://serverfault.com/questions/871984/forward-traffic-from-one-process-only)
> 
> ```
> sysct -w net.ipv4.conf.all.route_localnet=1`
> 
> iptables -t nat -A OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -m owner --uid-owner 0 -p tcp --dport 50000 -j DNAT --to-destination 127.0.0.1:8080
> ```

Moreover, iptables is obsolete in front of nftables...

**Comment by user-name-is-taken** [comment]
An

> ebpf

This seems to be the solution used by the [dae](https://github.com/daeuniverse/dae/tree/main) project which has " Support to split traffic by process name in local host" in its main README.

**Comment by user-name-is-taken** [comment]
The [dae](https://github.com/daeuniverse/dae/tree/main) project has " Support to split traffic by process name in local host" in its main README. It may be possible to copy their implementation.

**Comment by mhils** [comment]
Thanks for the pointer! We already did some initial prototyping to validate the ebpf parts (https://github.com/emanuele-em/mitmproxy_linux/). This was generally successful, so we have a plan to turn that into something useable. :)

**Comment by mhils** [comment]
Local Capture Mode for Linux is out now: https://mitmproxy.org/posts/local-capture/linux/ 🎉

**Comment by mastermach50** [comment]
Is it possible to filter out traffic by user? If not are there any plans to implement it?

There are several services running on my system as root and other users, but I only want to view the traffic from apps I started in my workspace.

**Comment by psparc82** [comment]
> Local Capture Mode for Linux is out now: https://mitmproxy.org/posts/local-capture/linux/ 🎉

does Linux local mode automatically install the mitmproxy CA cert? Does it change `/usr/local/share/ca-certificates` or anything else on the machine? Not sure how local mode presents certificates to clients, the clients must trust the mitmproxy CA cert somewhere...
