### ISSUE TITLE
Tracking Issue: MVP Capture Tab

### ISSUE THREAD

**Issue by lups2000** [mitmproxy/mitmproxy#6955]
### Overview

We're adding a new tab (**Capture**) to improve the user experience for mitmproxy's users. We're following the mockup we discussed [here](https://github.com/mitmproxy/mitmproxy/discussions/6868).

#### Current Status

- [x] Regular mode (just a toggle)
- [x] Local mode (simple input field)
- [x] Wireguard mode (just a toggle)
- [x] Reverse mode (just one)
- [x] Error handling
- [x] Change `listen_port` in the Regular mode
