### ISSUE TITLE
Tracking Issue: Capture Tab

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#7063]
Mitmweb is getting a new capture tab. See https://github.com/mitmproxy/mitmproxy/discussions/6868 for the original discussion and https://github.com/mitmproxy/mitmproxy/issues/6955 for the MVP. This issue collects everything for the first version to be called feature complete.

- [x] Display current status for each mode. We want to integrate what's currently in [web/src/js/components/CaptureSetup.tsx](https://github.com/mitmproxy/mitmproxy/blob/main/web/src/js/components/CaptureSetup.tsx) and remove that page entirely. The CaptureSetup page can just refer to the new tab and not display anything itself.
- [x] Add ⚙️ button for an "advanced configuration" popover.
- [x] Move listen_host / listen_port into popover.
- [x] Make sure local mode is hidden/greyed out/... on unsupported platforms.
- [x] Support for multiple reverse proxies.
- [x] Application selector with process names and icons for local redirect mode.
- [x] Add remaining proxy modes in "Advanced" category
  - [x] SOCKS proxy mode
  - [x] DNS server mode
  - [x] Upstream proxy mode
  - [x] Transparent mode

Minor Stuff:
- [x] Improve dropdown when selecting protocols.
- [x] Clicking on the label should activate the mode.
- [x] Reverse Proxy Mode needs a popover.
- [x] Highlight recommended modes visually, e.g. like [this](https://github.com/user-attachments/assets/9f2d2416-f79d-44e3-9a7b-9f2824aca6c3).
- [x] On unsupported platforms, show a greyed out "Local Redirect Mode" header with "This mode is only supported on Windows and Linux" in the list. I was super confused where local redirect mode was when starting mitmweb from WSL, which made me realize that just hiding it is bad UX.
- [x] Make it possible to add arbitrary strings in local mode, not just executables from the list.
- [x] Add cache headers for the executable icons endpoint.
- [x] Enabling both regular and local redirect mode on Windows (on MacOS as well) currently gives an incorrect "Cannot spawn multiple servers on the same address: *:8080" error.

**Comment by lups2000** [comment]
@mhils 🥳 🎉
